sudo: required
dist: trusty

cache:
    ccache: true
    apt: true
    directories:
        - sdk/gcc
        - sdk/binutils
        - sdk/cgen
        - sdk/epiphany-libs
        - sdk/gcc
        - sdk/gcc-infrastructure
        - sdk/gdb
        - sdk/newlib

language: c

before_install:
    - sudo apt-get update -qq
    - sudo apt-get upgrade -qq -o Dpkg::Options::="--force-confnew"
    - sudo apt-get install -qq -o Dpkg::Options::="--force-confnew"
      build-essential
    - sudo apt-get install -qq -o Dpkg::Options::="--force-confnew"
      bison
      flex
      g++-arm-linux-gnueabihf
      gcc-arm-linux-gnueabihf
      libgmp3-dev
      libncurses5-dev
      libmpc-dev
      libmpfr-dev
      locate
      texinfo
      wget
      xzip
      lzip
      zip
      guile-1.8

script:
    - mkdir -p sdk
    - mv * .* sdk || true
    - ./sdk/download-components.sh --download
    - ./sdk/.travis.sh

